### ISSUE TITLE
Fatal error: Call to undefined method WBW\Library\SMSMode\Provider\ApiProvider::getAuthentification()

### ISSUE THREAD

**Issue by hacktop** [webeweb/smsmode-library#1]
hi i have this issue with the last release
Fatal error: Call to undefined method WBW\Library\SMSMode\Provider\ApiProvider::getAuthentification()

maybe because off scading inherance

**Comment by webeweb** [comment]
Hello,

Take a look into sample folder, you can see the right method :

```php
$provider->getAuthentication()
```

Best regards
